# Generated by Django 4.0.1 on 2022-01-05 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0010_auto_20220104_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 22, 54, 59, 485900)),
        ),
    ]
