# Generated by Django 4.0.1 on 2022-01-05 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0011_appliances_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 6, 14, 9, 1234, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='appliances',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 6, 14, 8, 985233, tzinfo=utc)),
        ),
    ]
