# Generated by Django 4.0.1 on 2022-01-05 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_consumption_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 21, 22, 46, 628320)),
        ),
    ]
