# Generated by Django 4.0.1 on 2022-01-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_remove_consumption_value_alter_room_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date',
        ),
    ]
