# Generated by Django 4.0.1 on 2022-01-05 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_remove_room_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 22, 43, 17, 604946)),
        ),
    ]
