# Generated by Django 3.2.9 on 2021-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='maria@gmail.com', max_length=80),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Maria', max_length=80),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Aley', max_length=80),
        ),
    ]
