# Generated by Django 3.2.9 on 2021-11-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211123_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='maria@gmail.com', max_length=254),
        ),
    ]
